/** Public semantic color names. Values convey presentation only, never authority. */
export const PRESENTATION_COLORS = {
  dark: {
    '--app-bg': '#0f1115',
    '--surface-0': '#101318',
    '--surface-1': '#12151a',
    '--surface-2': '#15181e',
    '--surface-raised': '#181b21',
    '--surface-hover': '#20242c',
    '--surface-active': '#243142',
    '--border-subtle': '#282d36',
    '--border-strong': '#343a45',
    '--text-strong': '#edf0f5',
    '--text': '#c9ced7',
    '--text-muted': '#7f8898',
    '--accent': '#4d8fd8',
    '--accent-soft': '#29384a',
    '--viewer-bg': '#15181e',
    '--viewer-gutter': '#15181e',
    '--viewer-gutter-text': '#5f6877',
    '--code-border': '#242933',
    '--shadow': 'rgb(0 0 0 / 38%)',
    '--danger-text': '#dc7b82',
    '--warning-border': '#544632',
    '--warning-surface': '#211d16',
    '--warning-text': '#d8bd83',
    '--toolbar-text': '#d9dce2',
    '--toolbar-surface': '#181b21',
    '--text-secondary': '#aeb5c0',
    '--text-disabled': '#505865',
    '--panel-surface': '#15181e',
    '--chrome-surface': '#111419',
    '--navigation-active-surface': '#15181e',
    '--overlay-surface': 'rgb(5 7 10 / 72%)',
    '--accent-glow': 'rgb(77 143 216 / 42%)',
    '--accent-wash': 'rgb(51 83 122 / 16%)',
    '--accent-text': '#70a9e8',
    '--on-accent-text': '#f3f7fb',
    '--danger-border': '#653b42',
    '--danger-surface': '#24191c',
    '--success-text': '#7ccc91',
    '--success-surface': '#17261c',
    '--success-border': '#3b6547',
    '--inactive-text': '#998da5',
    '--inactive-surface': '#352b42',
    '--inactive-border': '#9675bc',
    '--code-inline-surface': '#20242c',
    '--code-inline-text': '#c9ced7',
    '--code-block-surface': '#101318',
    '--data-heading-surface': '#1b1f26',
    '--data-stripe-surface': '#181b21',
    '--image-checker-surface': '#171a20',
    '--image-canvas-surface': '#15181e',
    '--image-caption-surface': '#111419e8',
    '--image-shadow': 'rgb(0 0 0 / 30%)',
    '--data-warning-text': '#c8a76b',
    '--data-warning-surface': '#211d17',
    '--data-warning-border': '#343a45',
    '--change-removed-text': '#e69ba6',
    '--change-added-text': '#7bc5a3',
    '--change-removed-surface': '#231d24',
    '--change-added-surface': '#192720',
    '--change-removed-emphasis': '#53303b',
    '--change-added-emphasis': '#244c3c',
    '--selection-surface': '#3b5791',
    '--selection-muted-surface': '#202630',
    '--selection-muted-border': '#3c526c',
    '--syntax-key': '#9cdcfe',
    '--syntax-string': '#ce9178',
    '--syntax-number': '#b5cea8',
    '--syntax-boolean': '#569cd6',
    '--syntax-null': '#c586c0',
  },
  light: {
    '--app-bg': '#eef2f6',
    '--surface-0': '#f7f9fb',
    '--surface-1': '#ffffff',
    '--surface-2': '#f6f8fa',
    '--surface-raised': '#e9eef4',
    '--surface-hover': '#e5ebf2',
    '--surface-active': '#dbe9f8',
    '--border-subtle': '#d4dbe3',
    '--border-strong': '#bcc6d1',
    '--text-strong': '#17202b',
    '--text': '#34404d',
    '--text-muted': '#6b7785',
    '--accent': '#2f72b7',
    '--accent-soft': '#dbe9f8',
    '--viewer-bg': '#ffffff',
    '--viewer-gutter': '#f4f6f8',
    '--viewer-gutter-text': '#778391',
    '--code-border': '#d8dee6',
    '--shadow': 'rgb(31 43 55 / 18%)',
    '--danger-text': '#a53f49',
    '--warning-border': '#d4b16a',
    '--warning-surface': '#fff7e8',
    '--warning-text': '#80520d',
    '--toolbar-text': '#34404d',
    '--toolbar-surface': '#f7f9fb',
    '--text-secondary': '#6b7785',
    '--text-disabled': '#8993a0',
    '--panel-surface': '#ffffff',
    '--chrome-surface': '#f7f9fb',
    '--navigation-active-surface': '#dbe9f8',
    '--overlay-surface': 'rgb(5 7 10 / 72%)',
    '--accent-glow': 'rgb(47 114 183 / 42%)',
    '--accent-wash': 'rgb(47 114 183 / 8%)',
    '--accent-text': '#2f72b7',
    '--on-accent-text': '#ffffff',
    '--danger-border': '#d8a0a6',
    '--danger-surface': '#fff7f7',
    '--success-text': '#206a49',
    '--success-surface': '#eff9f3',
    '--success-border': '#a7cbb2',
    '--inactive-text': '#786687',
    '--inactive-surface': '#eee5f7',
    '--inactive-border': '#9675bc',
    '--code-inline-surface': '#e9eef4',
    '--code-inline-text': '#293747',
    '--code-block-surface': '#f6f8fa',
    '--data-heading-surface': '#f6f8fa',
    '--data-stripe-surface': '#f6f8fa',
    '--image-checker-surface': '#e8edf2',
    '--image-canvas-surface': '#f4f7fa',
    '--image-caption-surface': '#fffffff0',
    '--image-shadow': 'rgb(31 43 55 / 18%)',
    '--data-warning-text': '#765b16',
    '--data-warning-surface': '#fff8dd',
    '--data-warning-border': '#d7c79d',
    '--change-removed-text': '#ac344a',
    '--change-added-text': '#206a49',
    '--change-removed-surface': '#fdf2f4',
    '--change-added-surface': '#eff9f3',
    '--change-removed-emphasis': '#f4ccd3',
    '--change-added-emphasis': '#c7ead4',
    '--selection-surface': '#b4cef8',
    '--selection-muted-surface': '#dbe9f8',
    '--selection-muted-border': '#8faac5',
    '--syntax-key': '#0550ae',
    '--syntax-string': '#953800',
    '--syntax-number': '#116329',
    '--syntax-boolean': '#8250df',
    '--syntax-null': '#cf222e',
  },
} as const
export const PRESENTATION_COLOR_DEFAULTS = PRESENTATION_COLORS.dark
export type PresentationColorToken = keyof typeof PRESENTATION_COLOR_DEFAULTS
export const PRESENTATION_COLOR_TOKENS = Object.keys(
  PRESENTATION_COLOR_DEFAULTS,
) as PresentationColorToken[]
/** Resolved browser colors only; no URLs, variables, expressions or private CSS. */
export const PRESENTATION_COLOR_PATTERN =
  /^(?:#(?:[a-fA-F0-9]{3}|[a-fA-F0-9]{4}|[a-fA-F0-9]{6}|[a-fA-F0-9]{8})|(?:rgb|rgba|hsl|hsla|lab|lch|oklab|oklch)\([0-9.%+\-/,\s]+\)|color\((?:srgb|srgb-linear|display-p3|a98-rgb|prophoto-rgb|rec2020|xyz|xyz-d50|xyz-d65) [0-9.%+\-/,\s]+\))$/
